#ifndef KANGARU5_DETAIL_UNDEF_HPP
#define KANGARU5_DETAIL_UNDEF_HPP

#ifndef KANGARU5_DETAIL_DEFINE_HPP
#error "Must include define.hpp before including undef.hpp"
#endif

#undef KANGARU5_NO_UNIQUE_ADDRESS
#undef KANGARU5_FUNCTION_SIGNATURE
#undef KANGARU5_FWD
#undef KANGARU5_CONSTRUCTOR_T
#undef KANGARU5_INLINE
#undef KANGARU5_RVALUE_AMBIGUOUS
#undef KANGARU5_LVALUE_CONST_AMBIGUOUS
#undef KANGARU5_UNSAFE
#undef KANGARU5_UNSAFE_BLOCK
#undef KANGARU5_CONSTEXPR_VOIDSTAR
#undef KANGARU5_CONSTEVAL_PLACEHOLDER
#undef KANGARU5_CONSTEVAL

// We make those header re-includable
#undef KANGARU5_DETAIL_DEFINE_HPP
#undef KANGARU5_DETAIL_UNDEF_HPP

#endif // KANGARU5_DETAIL_UNDEF_HPP
