#ifndef KGR_KANGARU_INCLUDE_KANGARU_DETAIL_UNDEF
#define KGR_KANGARU_INCLUDE_KANGARU_DETAIL_UNDEF

#undef KGR_KANGARU_CXX17_NOEXCEPT
#undef KGR_KANGARU_CXX17_NOEXCEPT_FPTR
#undef KGR_KANGARU_USE_ALTERNATE_MAP_PROBE
#undef KGR_KANGARU_MSVC_DISABLE_VALIDATION_AUTOWIRE
#undef KGR_KANGARU_THROW
#undef KGR_KANGARU_MSVC_NO_DEPENDENT_TEMPLATE_KEYWORD
#undef KGR_KANGARU_MSVC_EXACT_DECLTYPE
#undef KGR_KANGARU_EMPTY_BASES
#undef KGR_KANGARU_FUNCTION_SIGNATURE

// These two header are meant to be included
// everytime they are needed since they cancel each other
#undef KGR_KANGARU_INCLUDE_KANGARU_DETAIL_UNDEF
#undef KGR_KANGARU_INCLUDE_KANGARU_DETAIL_DEFINE

#endif // KGR_KANGARU_INCLUDE_KANGARU_DETAIL_UNDEF
