#ifndef KANGARU5_KANGARU_HPP
#define KANGARU5_KANGARU_HPP

#include "detail/allocator.hpp"
#include "detail/any_source_of.hpp"
#include "detail/attributes.hpp"
#include "detail/cache.hpp"
#include "detail/cache_types.hpp"
#include "detail/concepts.hpp"
#include "detail/constructor.hpp"
#include "detail/container.hpp"
#include "detail/container_common.hpp"
#include "detail/ctti.hpp"
#include "detail/deducer.hpp"
#include "detail/exceptions.hpp"
#include "detail/heap_storage.hpp"
#include "detail/injector.hpp"
#include "detail/lazy.hpp"
#include "detail/murmur.hpp"
#include "detail/optional.hpp"
#include "detail/polymorphic_container.hpp"
#include "detail/polymorphic_source.hpp"
#include "detail/recursive_source.hpp"
#include "detail/source.hpp"
#include "detail/source_rebind.hpp"
#include "detail/source_reference_wrapper.hpp"
#include "detail/source_traits.hpp"
#include "detail/source_types.hpp"
#include "detail/type_traits.hpp"
#include "detail/utility.hpp"

#endif // KANGARU5_KANGARU_HPP
