name: All OS
on: [push, pull_request]

jobs:
  apple-clang:
    name: AppleClang ${{ matrix.xcode }} MacOS
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-15, macos-26]
        xcode: ["16.3", "16.4", "26.0", "26.1", "26.2"]
        exclude:
          - os: macos-15
            xcode: "26.0"
          - os: macos-15
            xcode: "26.1"
          - os: macos-15
            xcode: "26.2"
          - os: macos-26
            xcode: "16.3"
          - os: macos-26
            xcode: "16.4"

    steps:
      - uses: actions/checkout@v5

      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: ${{ matrix.xcode }}

      - name: get-cmake
        uses: lukka/get-cmake@v4.1.2

      - name: Run vcpkg
        uses: lukka/run-vcpkg@v11

      - name: 'Run CMake C++20'
        uses: lukka/run-cmake@v10
        with:
          configurePreset: 'ci-linux'
          buildPreset: 'ci-linux'
          testPreset: 'ci-linux'
          configurePresetAdditionalArgs: "['-DCMAKE_CXX_STANDARD=20']"

      - name: 'Run CMake C++23'
        uses: lukka/run-cmake@v10
        with:
          configurePreset: 'ci-linux'
          buildPreset: 'ci-linux'
          testPreset: 'ci-linux'
          configurePresetAdditionalArgs: "['-DCMAKE_CXX_STANDARD=23']"

      - name: 'Run CMake C++26'
        uses: lukka/run-cmake@v10
        with:
          configurePreset: 'ci-linux'
          buildPreset: 'ci-linux'
          testPreset: 'ci-linux'
          configurePresetAdditionalArgs: "['-DCMAKE_CXX_STANDARD=26']"

  linux-clang:
    name: Clang ${{ matrix.clang }} Linux
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        clang: [19, 20, 21, 22]

    steps:
      - uses: actions/checkout@v5

      - uses: DeterminateSystems/determinate-nix-action@v3
      - uses: nicknovitski/nix-develop@v1
        with:
          arguments: ".#ci-clang${{ matrix.clang }}"

      - name: 'Run CMake C++20'
        uses: lukka/run-cmake@v10
        with:
          configurePreset: 'ci-linux'
          buildPreset: 'ci-linux'
          testPreset: 'ci-linux'
          configurePresetAdditionalArgs: "['-DCMAKE_CXX_STANDARD=20']"

      - name: 'Run CMake C++23'
        uses: lukka/run-cmake@v10
        with:
          configurePreset: 'ci-linux'
          buildPreset: 'ci-linux'
          testPreset: 'ci-linux'
          configurePresetAdditionalArgs: "['-DCMAKE_CXX_STANDARD=23']"

      - name: 'Run CMake C++26'
        uses: lukka/run-cmake@v10
        with:
          configurePreset: 'ci-linux'
          buildPreset: 'ci-linux'
          testPreset: 'ci-linux'
          configurePresetAdditionalArgs: "['-DCMAKE_CXX_STANDARD=26']"

  linux-gcc-cxx-23:
    name: GCC ${{ matrix.gcc }} Linux
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        gcc: [13]

    steps:
      - uses: actions/checkout@v5

      - uses: DeterminateSystems/determinate-nix-action@v3
      - uses: nicknovitski/nix-develop@v1
        with:
          arguments: ".#ci-gcc${{ matrix.gcc }}"

      - name: 'Run CMake C++20'
        uses: lukka/run-cmake@v10
        with:
          configurePreset: 'ci-linux'
          buildPreset: 'ci-linux'
          testPreset: 'ci-linux'
          configurePresetAdditionalArgs: "['-DCMAKE_CXX_STANDARD=20']"

      - name: 'Run CMake C++23'
        uses: lukka/run-cmake@v10
        with:
          configurePreset: 'ci-linux'
          buildPreset: 'ci-linux'
          testPreset: 'ci-linux'
          configurePresetAdditionalArgs: "['-DCMAKE_CXX_STANDARD=23']"

  linux-gcc:
    name: GCC ${{ matrix.gcc }} Linux
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        gcc: [14, 15, 16]

    steps:
      - uses: actions/checkout@v5

      - uses: DeterminateSystems/determinate-nix-action@v3
      - uses: nicknovitski/nix-develop@v1
        with:
          arguments: ".#ci-gcc${{ matrix.gcc }}"

      - name: 'Run CMake C++20'
        uses: lukka/run-cmake@v10
        with:
          configurePreset: 'ci-linux'
          buildPreset: 'ci-linux'
          testPreset: 'ci-linux'
          configurePresetAdditionalArgs: "['-DCMAKE_CXX_STANDARD=20']"

      - name: 'Run CMake C++23'
        uses: lukka/run-cmake@v10
        with:
          configurePreset: 'ci-linux'
          buildPreset: 'ci-linux'
          testPreset: 'ci-linux'
          configurePresetAdditionalArgs: "['-DCMAKE_CXX_STANDARD=23']"

      - name: 'Run CMake C++26'
        uses: lukka/run-cmake@v10
        with:
          configurePreset: 'ci-linux'
          buildPreset: 'ci-linux'
          testPreset: 'ci-linux'
          configurePresetAdditionalArgs: "['-DCMAKE_CXX_STANDARD=26']"

  windows-msvc-2026:
    runs-on: windows-${{ matrix.windows }}-vs${{ matrix.vs }} C++${{ matrix.cxx }}
    name: MSVC ${{ matrix.vs }} Windows
    strategy:
      fail-fast: false
      matrix:
        vs: [2026]
        windows: [2025]
        cxx: [20, 23]

    steps:
      - uses: actions/checkout@v5

      - uses: egor-tensin/vs-shell@v2
        with:
          arch: x64

      - name: get-cmake
        uses: lukka/get-cmake@v4.1.2

      - name: Run vcpkg
        uses: lukka/run-vcpkg@v11

      - name: 'Run CMake C++${{ matrix.cxx }}'
        uses: lukka/run-cmake@v10
        with:
          configurePreset: 'ci-windows'
          buildPreset: 'ci-windows'
          testPreset: 'ci-windows'
          configurePresetAdditionalArgs: "['-DCMAKE_CXX_STANDARD=${{ matrix.cxx }}']"
          buildPresetAdditionalArgs: "['--', '-j2']"

